---
title: "Lab Report 1"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


# Question 1
Explore the dataset and answer the following questions:

## 1.1
What variables does the dataset contain? How many weeks are included for each variable in the dataset? (Hint: what function gives the column names? What function gives the number of rows in a data frame?)

## 1.2
What state are you from? What was the ILI in the 2nd week of the season for your state? (Note if you are from out of the States or Florida (the CDC did not have data for Florida that season), please use New York City instead).

## 1.3
Suppose you store the dataset in a variable called 'ili'. What do the outputs from the following commands represent? NOTE: Specify the date(s) and location(s); do not copy & paste the output.

### part a
ili [2, 6]

### part b
ili [30, 5:14]

### part c
ili [, 5]

### part d
ili [36, 'New.York.City'] (Note: R does not 'like' space in variable names, so replace space with '.' here)

# Question 2

# Question 3

# Question 4

# Question 5

# Question 6